### ISSUE TITLE
[meta] Reboot Data Patterns

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#73]
Overall discussion and get involved issues.
- [x] Recruit editors and contributors - please leave a comment below if you are interested in helping
- [x] #69 - convert over existing content to markdown and jekyll
- [x] #72 - new site theme 
- [ ] Plan of new content and call for content contributors
- [ ] Announce re-launch
- ...

**If you are interested in contributing please put a comment below**

**Comment by todrobbins** [comment]
Sign me up!

I can help with #69 and #72

**Comment by rufuspollock** [comment]
@todrobbins great - do you want to have a stab at #69 using pandoc or ...

**Comment by todrobbins** [comment]
@rgrp sure. Is there another repo with more content? I don't see anything in this one.

Also, are we going with Jekyll once we convert the old content?

**Comment by todrobbins** [comment]
Ah, just saw you tagged me about the old repo/branch. Thanks!

**Comment by seralf** [comment]
Hi!
If some extra help for pandoc/markdown is needed, please let me know if I can contribute!

I suggest also using [Haroopad](http://pad.haroopress.com/) for fine-grained editing (especially for images references)

How much content should be converted?

**Comment by rufuspollock** [comment]
@seralf great to have you help - please take a look at #69 along with @todrobbins - instructions on what to convert are in that issue and we can discuss there if not clear.

**Comment by rufuspollock** [comment]
@seralf @todrobbins how's this going? I'm going to move to #69.

**Comment by rufuspollock** [comment]
@seralf how are you doing? Are you able to help some more?

Also @todrobbins are you able to contribute - we are very close to having some nice working again here :-)

**Comment by seralf** [comment]
Hi Rufus, sorry for not giving new updates: I am moving slowly due to other
things, but I can contribute more if needed.

Last week I've made some more experiments with templating, but didn't have
yet something ready to submit, I think I have to study a little jekyll (I
suppose understanding how it works will require more time than actually
edit the files :-)

2015-07-28 12:39 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf re templating - we want to probably copy the approach of https://github.com/openspending/dotorg - this is jekyll based and use our latest template setup. We can probably literally copy and paste and then adapt.

**Comment by rufuspollock** [comment]
@seralf how are you doing here - i will move convo to site theming issue #72

**Comment by gsilvapt** [comment]
By the way, count me in as a contributor!

**Comment by rufuspollock** [comment]
FIXED. We are not go ...
